android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
project.android.compileSdk=37
project.android.minSdk=26
project.android.targetSdk=37
project.module-app.packageName=com.vstory.hook.rikkahub
project.module-app.versionName=2.0.0
project.module-app.versionCode=70
